<?php 
//UNA VEZ CREADA LAS TABLAS SE HACEN LOS INSERT
//PROVEEEDORES
INSERT INTO `PROVEEDORES`(`NUMERO`, `NOMBRE`, `DOMICILIO`, `LOCALIDAD`) 
VALUES (100,'PEREZ','PERON 876','QUILMES'),
(101,'GIMENEZ','MITRE 750','AVELLANEDA'),
(102,'AGUIRRE','BOEDO 634','BERNAL')
//PRODUCTOS
INSERT INTO `PRODUCTOS`(`PNUMERO`, 'PNOMBRE`, `PRECIO`, `TAMAÑO`) '
VALUES (1,'CARAMELOS','1.5','CHICO'),
(2,'CIGARRILLOS','45.89','MEDIANO'),
(3,'GASEOSA','15.80','GRANDE')
//ENVIOS
INSERT INTO `envios`(`NUMERO`, `PNUMERO`, `CANTIDAD`) 
VALUES (100,1,500),
(100,1,1500),
(100,3,100),
(101,2,55),
(101,3,225),
(102,1,600),
(102,3,300)
//EJERCICIO 03 CONSULTAS
1) SELECT * FROM `productos` ORDER BY productos.PNOMBRE ASC
2) SELECT * FROM `proveedores` WHERE LOCALIDAD='QUILMES'
3) SELECT * FROM `envios` WHERE CANTIDAD>=200 AND CANTIDAD<=300  o SELECT * FROM `envios` WHERE CANTIDAD BETWEEN 200 and 300
4) SELECT SUM(CANTIDAD) FROM `envios`
5) SELECT PNUMERO FROM `envios` LIMIT 3
6) SELECT proveedores.nombre as proveedores, productos.PNOMBRE as productos FROM `envios`,`productos`, `proveedores` WHERE envios.NUMERO= proveedores.NUMERO AND productos.PNUMERO= envios.PNUMERO
7)
?>